### ISSUE TITLE
Need to add a favicon

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/registry-api-active-docs#9]

**Comment by der** [comment]
Don't think it needs a separate favicon from the registry which hosts it.

**Comment by ijdickinson** [comment]
Action is to add, not create, a favicon. I just need to copy the current one

**Comment by ijdickinson** [comment]
@der I've looked at the current registry, and can't see a favicon. Are you saying that you don't think that a favicon is needed at all?

**Comment by der** [comment]
Hmmm, looks like I'm being confused by the Chrome cache.

There is a favicon (the old EA green circle favicon) in the source `/ldregistry/ui/assets/images/favicon.*` however that is not  currently linked to by root registry page.

I used to have a hand created registry icon (blue `R` on white background) which was being correctly linked to. All my copies of Chrome seem to have that cached. So I was seeing that favicon on the api-active-docs when served from a local registry image (I think because chrome will use the last one it saw up the URL path). Hence thinking nothing more was needed.

Sadly my copy of the original favicon seems to be corrupt.

Guess I should recreate it, add it to the two deployments, fix the missing link and then update this ticket.

**Comment by ijdickinson** [comment]
If you can send me a screenshot of the icon you had I can recreate it pretty easily
